version: "3"

services:
  app:
    build:
      context: app
    container_name: app
    volumes:
      - ./app:/usr/src/app
    depends_on:
      database:
        condition: "service_healthy"

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - app

  database:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: database
    restart: always
    tty: true
    volumes:
      - ./database:/docker-entrypoint-initdb.d/
      - ./mysql:/var/lib/mysql/
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  mysql:
    driver: local
